Add sorting
ChainSafe/api3-rust pull request #10
Opened 2022-03-30 12:17 UTC by ivanceras

Add a placeholder code for sorting U256 type.

2022-03-30 12:55 UTC, willeslau commented on common/src/lib.rs
> +    value: Uint256,
we might have to change this Uint256 to ethereum types

2022-03-30 13:03 UTC, willeslau requested changes

2022-03-30 13:03 UTC, willeslau commented on .devcontainer/Solana-Dockerfile
>  # Build a dummy program to bootstrap the BPF SDK (doing this speeds up builds).
might need to merge with main to resolve the conflicts

2022-03-31 05:56 UTC, ivanceras commented
I'll close this as there are many conflicts. This will be included in the other PR

2022-03-31 05:56 UTC, closed without merging